[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

DISABLE_UPDATE_PROMPT=true
export ZSH=$HOME/src/oh-my-zsh

ZSH_THEME="bira"

plugins=(git svn)

source $ZSH/oh-my-zsh.sh

export PATH="${HOME}/bin:${HOME}/.local/bin:${PATH}"
